### PR TITLE
Adding ChildStartableMode.BACKGROUND_LATE to host entities.

### PR DESCRIPTION
**Pull request by kiuby88**
Starting children entities when a parent is started.

### CODE REVIEW

**Comment by kiuby88** [comment]
@robertgmoss, could you take a look please?

**Comment by sjcorbett** [comment]
@kiuby88 What is the benefit of enforcing this mode?

**Comment by kiuby88** [comment]
@sjcorbett , we could use any foreground or background mode in order to start the entities' children.

**Comment by andreaturli** [comment]
+1 @kiuby88 thanks!

**Comment by sjcorbett** [comment]
@andreaturli The build error is fixed on master so you are ok to merge this.

**Comment by andreaturli** [comment]
ok thanks @sjcorbett, merging now.

**Pull request merged**
