### PR TITLE
Fix/dsl management in policies

### PR DESCRIPTION
**Pull request by kiuby88**
Interprets DSL in policy properties.
 `testConcatFunctionInTopology()` was disabled according to [alien4cloud/alien4cloud#68](https://github.com/alien4cloud/alien4cloud/issues/68)

### CODE REVIEW

**Comment by sjcorbett** [comment]
@kiuby88 Can you describe what you are fixing / why we want to do this? The Brooklyn approach is to leave this kind of resolution until the value is required (by something calling `.sensors().get(..)` or `.config().get(..)`).

**Comment by kiuby88** [comment]
Thanks a lot for your reply, @sjcorbett 

The problem was that DSLs were avoided during policies configuration. For example, autoscaler policy metric `ConfigKey` was configured using a simple string, [here is an example](https://github.com/cloudsoft/brooklyn-tosca/blob/master/brooklyn-tosca-transformer/src/test/java/io/cloudsoft/tosca/a4c/brooklyn/ToscaTypePlanTransformerIntegrationTest.java#L248-L250), but I think it does not make sense.
Then, I thought it could be necessary to apply CAMP interpreters in order to find DSLs, so I followed the same strategy that `ConfigKeys` (and `Flags`) resolution (using `CampCatalogUtils.getCampPlatform(mgmt).pdp().applyInterpreters(...))`.

Then, when [metric](https://github.com/kiuby88/brooklyn-tosca/blob/fix/dsl-management-in-policies/brooklyn-tosca-transformer/src/test/resources/templates/autoscaling.policies.tosca.yaml#L32-32) is resolved applying interpreters directly a `Sensor` is retrieved. As you have mentioned I expected to find a DSL object something like [DslFormatString](https://github.com/kiuby88/brooklyn-server/blob/a721273c6eac9f969752babba86d249d97611fac/camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/methods/BrooklynDslCommon.java#L217-217) which is resolved during entity starting process.
I thought I was not using `CampCatalogUtils.getCampPlatform(mgmt).pdp().applyInterpreters(...))` correctly, but I took a look to some policies examples, such as [this one](https://github.com/kiuby88/brooklyn-library/blob/master/qa/src/test/java/org/apache/brooklyn/qa/camp/JavaWebAppsIntegrationTest.java#L240-240) where [this yaml](https://github.com/kiuby88/brooklyn-library/blob/master/qa/src/test/resources/java-web-app-and-db-with-policy.yaml) is processed and an `AutoScalerPolicy` instance contains a `DynamicWebAppCluster.REQUESTS_PER_SECOND_IN_WINDOW_PER_NODE` as a metric (and this policy instance is not started). I also debugged [this example](https://github.com/kiuby88/brooklyn-library/blob/master/software/webapp/src/test/java/org/apache/brooklyn/entity/webapp/TomcatAutoScalerPolicyTest.java#L73) and I found the same result. So, I thought that `CampCatalogUtils.getCampPlatform(mgmt).pdp().applyInterpreters(...))` resolvers `$brooklyn:sensor...` retrieves a Sensor directly.

In any case, I think policy properties should be interpreted by Pdp interpreters in order to avoid something like [this](https://github.com/cloudsoft/brooklyn-tosca/blob/master/brooklyn-tosca-transformer/src/test/java/io/cloudsoft/tosca/a4c/brooklyn/ToscaTypePlanTransformerIntegrationTest.java#L248-L250). So, I think I found a issue but if this PR it is not correct I can close and open another one following your advice :-)

Again, thanks a lot for your reply @sjcorbett

**Comment by andreaturli** [comment]
any update on this @sjcorbett ? do you need more / different details from @kiuby88 ?

**Comment by sjcorbett** [comment]
Sorry for leaving this for too long.

Thank you for your explanation. 

The key point is that we are acting on the policy _spec_, not the policy itself. In the same way as we configure entities we can use [dependent configuration](https://brooklyn.apache.org/v/latest/concepts/dependent-configuration.html) to set deferred values. Brooklyn will not block for their result (whether a sensor from `$brooklyn:sensor` or a value from an `attributeWhenReady`) until something (probably the policy itself) calls `.config().get(KEY)`. 

The changes in this PR have all policy configuration resolved before an application is started. This would mean that blueprints like the following (in non-TOSCA format) would cause `BrooklynToscaPolicyDecorator` to block forever:

``` yaml
services:
- type: ...
  id: database  

- type: ...
  brooklyn.policies:
  - type: ...
    brooklyn.config:
      key: $brooklyn:component("database").attributeWhenReady("address")
```

The difference between the changes here and the test in `JavaWebAppsIntegrationTest` is that you are asserting against the values on the spec whereas the test is asserting against the policy created from the spec.

**Comment by kiuby88** [comment]
Thanks a lot four your replies, @andreaturli and @sjcorbett
I get your point @sjcorbett and I agree. I wanted to avoid a String where a DSL object is expected. For example, [this autoscalerPolicy](https://github.com/cloudsoft/brooklyn-tosca/blob/137b5928da296f2adb8efdd50f7ac5473a9297ee/brooklyn-tosca-transformer/src/test/java/io/cloudsoft/tosca/a4c/brooklyn/ToscaTypePlanTransformerIntegrationTest.java#L246) has a String instead of a sensor. I will take a look and update the PR.

**Comment by andreaturli** [comment]
@kiuby88 - instead of updating the PR, can you please run your use case without this patch and report the error you are getting back, maybe?

**Comment by kiuby88** [comment]
Sure, if [this application](https://github.com/kiuby88/brooklyn-tosca/blob/a346e611ff26f4fb3eea0fc690ea08d8f6e36c27/brooklyn-tosca-transformer/src/test/resources/templates/autoscaling.policies.tosca.yaml) is deployed, the policy will not work. You ca see that the a sensor is required as the metric in autoscaler policy:

```
  groups:
    add_brooklyn_location:
      members: [ cluster ]
      policies:
      - brooklyn.location: localhost
      - autoscaling:
          type: org.apache.brooklyn.policy.autoscaling.AutoScalerPolicy
          metric: $brooklyn:sensor("org.apache.brooklyn.entity.webapp.DynamicWebAppCluster", "webapp.reqs.perSec.windowed.perNode")
          metricLowerBound: 10
          metricUpperBound: 100
          minPoolSize: 1
          maxPoolSize: 5
```

In this case, we use a `sensor` DSL to obtain the expected sensor. However, the DSL String is not processed during transformation process and the `AutoScalerPolicy` receives the following string as the metric `$brooklyn:sensor("org.apache.brooklyn.entity.webapp.DynamicWebAppCluster", "webapp.reqs.perSec.windowed.perNode")`. This does not produce any error but the policy cannot work because it does not see any sensor value. 
I do not know if this message solves your question @andreaturli

**Comment by andreaturli** [comment]
it doesn't sounds like a bug but it is behaving as documented at https://brooklyn.apache.org/v/latest/yaml/yaml-reference.html#dsl-commands

The value of the sensor is returned using "attributeWhenReady" not "sensor"

Could you try with 
`
$brooklyn:attributeWhenReady("org.apache.brooklyn.entity.webapp.DynamicWebAppCluster","webapp.reqs.perSec.windowed.perNode")
`
instead of
`
$brooklyn:sensor("org.apache.brooklyn.entity.webapp.DynamicWebAppCluster", "webapp.reqs.perSec.windowed.perNode")
`

**Comment by kiuby88** [comment]
Hi, 

finally @andreaturli helped me to find the solution. I was trying to get the sensor through a DSL. But I should use some like this: 

```
 - type: org.apache.brooklyn.policy.autoscaling.AutoScalerPolicy
    brooklyn.config:
      metric: webapp.reqs.perSec.perNode
      metricUpperBound: 3
      metricLowerBound: 1
      resizeUpStabilizationDelay: 2s
      resizeDownStabilizationDelay: 1m
      maxPoolSize: 3
```

So, DSLs are not required. Then, I can close this PR. Thanks a lot for your replies.

**Pull request closed without merging**
