### PR TITLE
Adding artifacts support using a Modifier

### PR DESCRIPTION
**Pull request by kiuby88**
Support Artifacts using a modifier

### CODE REVIEW

**Comment by sjcorbett** [comment]
@kiuby88 What is your logic behind this change? I think you should use `properties` for values that should be set as config keys.

**Comment by sjcorbett** [comment]
We're using [RuntimeEnvironmentModifier](https://github.com/cloudsoft/brooklyn-tosca/blob/1febb29c0310fd428e26e957c7d1942a7e42552f/brooklyn-tosca-transformer/src/main/java/io/cloudsoft/tosca/a4c/brooklyn/spec/RuntimeEnvironmentModifier.java) to handle artifacts. At the moment it's disabled pending some required fixes.

**Comment by kiuby88** [comment]
@sjcorbett, thanks for your reply.

I just wanted to add the capability for describing the artifacts as TOSCA describes. I think it is a interesting feature. 
Currently I am pointing the artifacts using the nodetemplate properties but I thought that it could be better using the artifacts support. In any case, I did not know the [ RuntimeEnvironmentModifier ](https://github.com/cloudsoft/brooklyn-tosca/blob/1febb29c0310fd428e26e957c7d1942a7e42552f/brooklyn-tosca-transformer/src/main/java/io/cloudsoft/tosca/a4c/brooklyn/spec/RuntimeEnvironmentModifier.java), I should add the artifacts support to this class. Sorry, my fault.

If you think this feature is interesting we can wait to fix [ RuntimeEnvironmentModifier ](https://github.com/cloudsoft/brooklyn-tosca/blob/1febb29c0310fd428e26e957c7d1942a7e42552f/brooklyn-tosca-transformer/src/main/java/io/cloudsoft/tosca/a4c/brooklyn/spec/RuntimeEnvironmentModifier.java) and try to add the artifacts support. If you think it is not useful we can avoid this proposal.
WDYT?

**Comment by sjcorbett** [comment]
I'd prefer RuntimeEnvironmentModifier to be improved. Artefacts shouldn't (certainly don't need to) be set as config keys on entities. If you need a value as a config key use a property.

**Pull request closed without merging**
